import type { Workshop } from "@/types/workshop";

export const WORKSHOPS: Workshop[] = [
  {
    id:                "21-consignas",
    title:             "21 Consignas para Brillar",
    slug:              "21-consignas",
    description:       "21 consignas de escritura creativa entregadas por email para despertar tu voz y tu historia.",
    modality:          "online",
    duration:          "21 emails a tu ritmo",
    frequency:         "A tu ritmo",
    price:             undefined,
    payment_type:      "whatsapp",
    registration_type: "interest",
    status:            "open",
    cta_label:         "QUIERO ANOTARME",
  },
  {
    id:                "mi-historia",
    title:             "Mi Historia es de Novela",
    slug:              "mi-historia-es-de-novela",
    description:       "Taller intensivo para escribir tu historia personal con profundidad y técnica narrativa.",
    modality:          "online",
    duration:          "A confirmar",
    frequency:         "A confirmar",
    price:             undefined,
    payment_type:      "whatsapp",
    registration_type: "interest",
    status:            "on_request",
    cta_label:         "QUIERO ANOTARME",
  },
  {
    id:                "coaching",
    title:             "Coaching 1:1 con Silvina",
    slug:              "coaching-1-a-1",
    description:       "Sesiones individuales de escritura y orientación narrativa con acompañamiento personalizado.",
    modality:          "online",
    duration:          "Sesiones de 60 min",
    frequency:         "A coordinar",
    price:             undefined,
    payment_type:      "calendly",
    registration_type: "discovery_call",
    status:            "on_request",
    cta_label:         "CONSULTAR DISPONIBILIDAD",
  },
  {
    id:                "comunidad",
    title:             "Comunidad de Escritura Creativa",
    slug:              "comunidad",
    description:       "Espacio online para escritoras y escritores que quieren escribir acompañados, sin presión.",
    modality:          "online",
    duration:          "Encuentros regulares",
    frequency:         "Semanal / quincenal",
    price:             undefined,
    payment_type:      "whatsapp",
    registration_type: "interest",
    status:            "open",
    cta_label:         "QUIERO SUMARME",
  },
  {
    id:                "grupo-creatividad",
    title:             "Grupo de Creatividad",
    slug:              "grupo-creatividad",
    description:       "Grupo pequeño de escritura y creatividad con feedback, lectura compartida y ejercicios guiados.",
    modality:          "ambas",
    duration:          "A confirmar",
    frequency:         "Semanal",
    price:             undefined,
    payment_type:      "whatsapp",
    registration_type: "interest",
    status:            "on_request",
    cta_label:         "QUIERO ANOTARME",
  },
  {
    id:                "grupo-lectura",
    title:             "Grupo de Lectura",
    slug:              "grupo-lectura",
    description:       "Grupo de lectura guiado por Silvina con análisis, conversación y ejercicios inspirados en los libros.",
    modality:          "ambas",
    duration:          "A confirmar",
    frequency:         "Quincenal / mensual",
    price:             undefined,
    payment_type:      "whatsapp",
    registration_type: "interest",
    status:            "on_request",
    cta_label:         "QUIERO ANOTARME",
  },
];

export function getWorkshop(idOrSlug: string): Workshop | undefined {
  return WORKSHOPS.find((w) => w.id === idOrSlug || w.slug === idOrSlug);
}
